
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/gamblinggame 

module add_unsigned_29(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_0, n_1, n_3, n_5, n_7, n_9, n_11, n_13;
  wire n_15, n_17, n_19, n_21, n_23, n_25, n_27, n_29;
  wire n_31, n_33, n_35, n_37, n_39, n_41, n_43, n_45;
  wire n_47, n_49, n_51, n_53, n_55, n_57, n_59, n_61;
  XNOR2_X1 g746(.A1 (n_61), .A2 (n_0), .ZN (Z[31]));
  FA_X1 g747(.A (B[30]), .B (A[30]), .CI (n_59), .CO (n_61), .S
       (Z[30]));
  FA_X1 g748(.A (B[29]), .B (A[29]), .CI (n_57), .CO (n_59), .S
       (Z[29]));
  FA_X1 g749(.A (B[28]), .B (A[28]), .CI (n_55), .CO (n_57), .S
       (Z[28]));
  FA_X1 g750(.A (B[27]), .B (A[27]), .CI (n_53), .CO (n_55), .S
       (Z[27]));
  FA_X1 g751(.A (B[26]), .B (A[26]), .CI (n_51), .CO (n_53), .S
       (Z[26]));
  FA_X1 g752(.A (B[25]), .B (A[25]), .CI (n_49), .CO (n_51), .S
       (Z[25]));
  FA_X1 g753(.A (B[24]), .B (A[24]), .CI (n_47), .CO (n_49), .S
       (Z[24]));
  FA_X1 g754(.A (B[23]), .B (A[23]), .CI (n_45), .CO (n_47), .S
       (Z[23]));
  FA_X1 g755(.A (B[22]), .B (A[22]), .CI (n_43), .CO (n_45), .S
       (Z[22]));
  FA_X1 g756(.A (B[21]), .B (A[21]), .CI (n_41), .CO (n_43), .S
       (Z[21]));
  FA_X1 g757(.A (B[20]), .B (A[20]), .CI (n_39), .CO (n_41), .S
       (Z[20]));
  FA_X1 g758(.A (B[19]), .B (A[19]), .CI (n_37), .CO (n_39), .S
       (Z[19]));
  FA_X1 g759(.A (B[18]), .B (A[18]), .CI (n_35), .CO (n_37), .S
       (Z[18]));
  FA_X1 g760(.A (B[17]), .B (A[17]), .CI (n_33), .CO (n_35), .S
       (Z[17]));
  FA_X1 g761(.A (B[16]), .B (A[16]), .CI (n_31), .CO (n_33), .S
       (Z[16]));
  FA_X1 g762(.A (B[15]), .B (A[15]), .CI (n_29), .CO (n_31), .S
       (Z[15]));
  FA_X1 g763(.A (B[14]), .B (A[14]), .CI (n_27), .CO (n_29), .S
       (Z[14]));
  FA_X1 g764(.A (B[13]), .B (A[13]), .CI (n_25), .CO (n_27), .S
       (Z[13]));
  FA_X1 g765(.A (B[12]), .B (A[12]), .CI (n_23), .CO (n_25), .S
       (Z[12]));
  FA_X1 g766(.A (B[11]), .B (A[11]), .CI (n_21), .CO (n_23), .S
       (Z[11]));
  FA_X1 g767(.A (B[10]), .B (A[10]), .CI (n_19), .CO (n_21), .S
       (Z[10]));
  FA_X1 g768(.A (B[9]), .B (A[9]), .CI (n_17), .CO (n_19), .S (Z[9]));
  FA_X1 g769(.A (B[8]), .B (A[8]), .CI (n_15), .CO (n_17), .S (Z[8]));
  FA_X1 g770(.A (B[7]), .B (A[7]), .CI (n_13), .CO (n_15), .S (Z[7]));
  FA_X1 g771(.A (B[6]), .B (A[6]), .CI (n_11), .CO (n_13), .S (Z[6]));
  FA_X1 g772(.A (B[5]), .B (A[5]), .CI (n_9), .CO (n_11), .S (Z[5]));
  FA_X1 g773(.A (B[4]), .B (A[4]), .CI (n_7), .CO (n_9), .S (Z[4]));
  FA_X1 g774(.A (B[3]), .B (A[3]), .CI (n_5), .CO (n_7), .S (Z[3]));
  FA_X1 g775(.A (B[2]), .B (A[2]), .CI (n_3), .CO (n_5), .S (Z[2]));
  FA_X1 g776(.A (B[1]), .B (A[1]), .CI (n_1), .CO (n_3), .S (Z[1]));
  HA_X1 g777(.A (B[0]), .B (A[0]), .CO (n_1), .S (Z[0]));
  XNOR2_X1 g778(.A1 (A[31]), .A2 (B[31]), .ZN (n_0));
endmodule

module add_unsigned_29_18(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_0, n_1, n_3, n_5, n_7, n_9, n_11, n_13;
  wire n_15, n_17, n_19, n_21, n_23, n_25, n_27, n_29;
  wire n_31, n_33, n_35, n_37, n_39, n_41, n_43, n_45;
  wire n_47, n_49, n_51, n_53, n_55, n_57, n_59, n_61;
  XNOR2_X1 g746(.A1 (n_61), .A2 (n_0), .ZN (Z[31]));
  FA_X1 g747(.A (B[30]), .B (A[30]), .CI (n_59), .CO (n_61), .S
       (Z[30]));
  FA_X1 g748(.A (B[29]), .B (A[29]), .CI (n_57), .CO (n_59), .S
       (Z[29]));
  FA_X1 g749(.A (B[28]), .B (A[28]), .CI (n_55), .CO (n_57), .S
       (Z[28]));
  FA_X1 g750(.A (B[27]), .B (A[27]), .CI (n_53), .CO (n_55), .S
       (Z[27]));
  FA_X1 g751(.A (B[26]), .B (A[26]), .CI (n_51), .CO (n_53), .S
       (Z[26]));
  FA_X1 g752(.A (B[25]), .B (A[25]), .CI (n_49), .CO (n_51), .S
       (Z[25]));
  FA_X1 g753(.A (B[24]), .B (A[24]), .CI (n_47), .CO (n_49), .S
       (Z[24]));
  FA_X1 g754(.A (B[23]), .B (A[23]), .CI (n_45), .CO (n_47), .S
       (Z[23]));
  FA_X1 g755(.A (B[22]), .B (A[22]), .CI (n_43), .CO (n_45), .S
       (Z[22]));
  FA_X1 g756(.A (B[21]), .B (A[21]), .CI (n_41), .CO (n_43), .S
       (Z[21]));
  FA_X1 g757(.A (B[20]), .B (A[20]), .CI (n_39), .CO (n_41), .S
       (Z[20]));
  FA_X1 g758(.A (B[19]), .B (A[19]), .CI (n_37), .CO (n_39), .S
       (Z[19]));
  FA_X1 g759(.A (B[18]), .B (A[18]), .CI (n_35), .CO (n_37), .S
       (Z[18]));
  FA_X1 g760(.A (B[17]), .B (A[17]), .CI (n_33), .CO (n_35), .S
       (Z[17]));
  FA_X1 g761(.A (B[16]), .B (A[16]), .CI (n_31), .CO (n_33), .S
       (Z[16]));
  FA_X1 g762(.A (B[15]), .B (A[15]), .CI (n_29), .CO (n_31), .S
       (Z[15]));
  FA_X1 g763(.A (B[14]), .B (A[14]), .CI (n_27), .CO (n_29), .S
       (Z[14]));
  FA_X1 g764(.A (B[13]), .B (A[13]), .CI (n_25), .CO (n_27), .S
       (Z[13]));
  FA_X1 g765(.A (B[12]), .B (A[12]), .CI (n_23), .CO (n_25), .S
       (Z[12]));
  FA_X1 g766(.A (B[11]), .B (A[11]), .CI (n_21), .CO (n_23), .S
       (Z[11]));
  FA_X1 g767(.A (B[10]), .B (A[10]), .CI (n_19), .CO (n_21), .S
       (Z[10]));
  FA_X1 g768(.A (B[9]), .B (A[9]), .CI (n_17), .CO (n_19), .S (Z[9]));
  FA_X1 g769(.A (B[8]), .B (A[8]), .CI (n_15), .CO (n_17), .S (Z[8]));
  FA_X1 g770(.A (B[7]), .B (A[7]), .CI (n_13), .CO (n_15), .S (Z[7]));
  FA_X1 g771(.A (B[6]), .B (A[6]), .CI (n_11), .CO (n_13), .S (Z[6]));
  FA_X1 g772(.A (B[5]), .B (A[5]), .CI (n_9), .CO (n_11), .S (Z[5]));
  FA_X1 g773(.A (B[4]), .B (A[4]), .CI (n_7), .CO (n_9), .S (Z[4]));
  FA_X1 g774(.A (B[3]), .B (A[3]), .CI (n_5), .CO (n_7), .S (Z[3]));
  FA_X1 g775(.A (B[2]), .B (A[2]), .CI (n_3), .CO (n_5), .S (Z[2]));
  FA_X1 g776(.A (B[1]), .B (A[1]), .CI (n_1), .CO (n_3), .S (Z[1]));
  HA_X1 g777(.A (B[0]), .B (A[0]), .CO (n_1), .S (Z[0]));
  XNOR2_X1 g778(.A1 (A[31]), .A2 (B[31]), .ZN (n_0));
endmodule

module vDFFRL_n32_27(clk, D, Q, reset, load);
  input clk, reset, load;
  input [31:0] D;
  output [31:0] Q;
  wire clk, reset, load;
  wire [31:0] D;
  wire [31:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_65), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[10] (.SN (1'b1), .CLK (clk), .D (n_53), .Q (Q[10]));
  DFFSNQ_X1 \Q_reg[11] (.SN (1'b1), .CLK (clk), .D (n_49), .Q (Q[11]));
  DFFSNQ_X1 \Q_reg[12] (.SN (1'b1), .CLK (clk), .D (n_39), .Q (Q[12]));
  DFFSNQ_X1 \Q_reg[13] (.SN (1'b1), .CLK (clk), .D (n_35), .Q (Q[13]));
  DFFSNQ_X1 \Q_reg[14] (.SN (1'b1), .CLK (clk), .D (n_31), .Q (Q[14]));
  DFFSNQ_X1 \Q_reg[15] (.SN (1'b1), .CLK (clk), .D (n_23), .Q (Q[15]));
  DFFSNQ_X1 \Q_reg[16] (.SN (1'b1), .CLK (clk), .D (n_19), .Q (Q[16]));
  DFFSNQ_X1 \Q_reg[17] (.SN (1'b1), .CLK (clk), .D (n_17), .Q (Q[17]));
  DFFSNQ_X1 \Q_reg[18] (.SN (1'b1), .CLK (clk), .D (n_15), .Q (Q[18]));
  DFFSNQ_X1 \Q_reg[19] (.SN (1'b1), .CLK (clk), .D (n_13), .Q (Q[19]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_11), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[20] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[20]));
  DFFSNQ_X1 \Q_reg[21] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[21]));
  DFFSNQ_X1 \Q_reg[22] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[22]));
  DFFSNQ_X1 \Q_reg[23] (.SN (1'b1), .CLK (clk), .D (n_63), .Q (Q[23]));
  DFFSNQ_X1 \Q_reg[24] (.SN (1'b1), .CLK (clk), .D (n_61), .Q (Q[24]));
  DFFSNQ_X1 \Q_reg[25] (.SN (1'b1), .CLK (clk), .D (n_59), .Q (Q[25]));
  DFFSNQ_X1 \Q_reg[26] (.SN (1'b1), .CLK (clk), .D (n_57), .Q (Q[26]));
  DFFSNQ_X1 \Q_reg[27] (.SN (1'b1), .CLK (clk), .D (n_55), .Q (Q[27]));
  DFFSNQ_X1 \Q_reg[28] (.SN (1'b1), .CLK (clk), .D (n_51), .Q (Q[28]));
  DFFSNQ_X1 \Q_reg[29] (.SN (1'b1), .CLK (clk), .D (n_47), .Q (Q[29]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_45), .Q (Q[2]));
  DFFSNQ_X1 \Q_reg[30] (.SN (1'b1), .CLK (clk), .D (n_43), .Q (Q[30]));
  DFFSNQ_X1 \Q_reg[31] (.SN (1'b1), .CLK (clk), .D (n_41), .Q (Q[31]));
  DFFSNQ_X1 \Q_reg[3] (.SN (1'b1), .CLK (clk), .D (n_37), .Q (Q[3]));
  DFFSNQ_X1 \Q_reg[4] (.SN (1'b1), .CLK (clk), .D (n_33), .Q (Q[4]));
  DFFSNQ_X1 \Q_reg[5] (.SN (1'b1), .CLK (clk), .D (n_29), .Q (Q[5]));
  DFFSNQ_X1 \Q_reg[6] (.SN (1'b1), .CLK (clk), .D (n_27), .Q (Q[6]));
  DFFSNQ_X1 \Q_reg[7] (.SN (1'b1), .CLK (clk), .D (n_25), .Q (Q[7]));
  DFFSNQ_X1 \Q_reg[8] (.SN (1'b1), .CLK (clk), .D (n_67), .Q (Q[8]));
  DFFSNQ_X1 \Q_reg[9] (.SN (1'b1), .CLK (clk), .D (n_21), .Q (Q[9]));
  INV_X1 g838(.I (n_66), .ZN (n_67));
  AOI22_X1 g839(.A1 (n_2), .A2 (Q[8]), .B1 (n_3), .B2 (D[8]), .ZN
       (n_66));
  INV_X1 g840(.I (n_64), .ZN (n_65));
  AOI22_X1 g841(.A1 (n_2), .A2 (Q[0]), .B1 (n_3), .B2 (D[0]), .ZN
       (n_64));
  INV_X1 g842(.I (n_62), .ZN (n_63));
  AOI22_X1 g843(.A1 (n_2), .A2 (Q[23]), .B1 (n_3), .B2 (D[23]), .ZN
       (n_62));
  INV_X1 g844(.I (n_60), .ZN (n_61));
  AOI22_X1 g845(.A1 (n_2), .A2 (Q[24]), .B1 (n_3), .B2 (D[24]), .ZN
       (n_60));
  INV_X1 g846(.I (n_58), .ZN (n_59));
  AOI22_X1 g847(.A1 (n_2), .A2 (Q[25]), .B1 (n_3), .B2 (D[25]), .ZN
       (n_58));
  INV_X1 g848(.I (n_56), .ZN (n_57));
  AOI22_X1 g849(.A1 (n_2), .A2 (Q[26]), .B1 (n_3), .B2 (D[26]), .ZN
       (n_56));
  INV_X1 g850(.I (n_54), .ZN (n_55));
  AOI22_X1 g851(.A1 (n_2), .A2 (Q[27]), .B1 (n_3), .B2 (D[27]), .ZN
       (n_54));
  INV_X1 g852(.I (n_52), .ZN (n_53));
  AOI22_X1 g853(.A1 (n_2), .A2 (Q[10]), .B1 (n_3), .B2 (D[10]), .ZN
       (n_52));
  INV_X1 g854(.I (n_50), .ZN (n_51));
  AOI22_X1 g855(.A1 (n_2), .A2 (Q[28]), .B1 (n_3), .B2 (D[28]), .ZN
       (n_50));
  INV_X1 g856(.I (n_48), .ZN (n_49));
  AOI22_X1 g857(.A1 (n_2), .A2 (Q[11]), .B1 (n_3), .B2 (D[11]), .ZN
       (n_48));
  INV_X1 g858(.I (n_46), .ZN (n_47));
  AOI22_X1 g859(.A1 (n_2), .A2 (Q[29]), .B1 (n_3), .B2 (D[29]), .ZN
       (n_46));
  INV_X1 g860(.I (n_44), .ZN (n_45));
  AOI22_X1 g861(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_44));
  INV_X1 g862(.I (n_42), .ZN (n_43));
  AOI22_X1 g863(.A1 (n_2), .A2 (Q[30]), .B1 (n_3), .B2 (D[30]), .ZN
       (n_42));
  INV_X1 g864(.I (n_40), .ZN (n_41));
  AOI22_X1 g865(.A1 (n_2), .A2 (Q[31]), .B1 (n_3), .B2 (D[31]), .ZN
       (n_40));
  INV_X1 g866(.I (n_38), .ZN (n_39));
  AOI22_X1 g867(.A1 (n_2), .A2 (Q[12]), .B1 (n_3), .B2 (D[12]), .ZN
       (n_38));
  INV_X1 g868(.I (n_36), .ZN (n_37));
  AOI22_X1 g869(.A1 (n_2), .A2 (Q[3]), .B1 (n_3), .B2 (D[3]), .ZN
       (n_36));
  INV_X1 g870(.I (n_34), .ZN (n_35));
  AOI22_X1 g871(.A1 (n_2), .A2 (Q[13]), .B1 (n_3), .B2 (D[13]), .ZN
       (n_34));
  INV_X1 g872(.I (n_32), .ZN (n_33));
  AOI22_X1 g873(.A1 (n_2), .A2 (Q[4]), .B1 (n_3), .B2 (D[4]), .ZN
       (n_32));
  INV_X1 g874(.I (n_30), .ZN (n_31));
  AOI22_X1 g875(.A1 (n_2), .A2 (Q[14]), .B1 (n_3), .B2 (D[14]), .ZN
       (n_30));
  INV_X1 g876(.I (n_28), .ZN (n_29));
  AOI22_X1 g877(.A1 (n_2), .A2 (Q[5]), .B1 (n_3), .B2 (D[5]), .ZN
       (n_28));
  INV_X1 g878(.I (n_26), .ZN (n_27));
  AOI22_X1 g879(.A1 (n_2), .A2 (Q[6]), .B1 (n_3), .B2 (D[6]), .ZN
       (n_26));
  INV_X1 g880(.I (n_24), .ZN (n_25));
  AOI22_X1 g881(.A1 (n_2), .A2 (Q[7]), .B1 (n_3), .B2 (D[7]), .ZN
       (n_24));
  INV_X1 g882(.I (n_22), .ZN (n_23));
  AOI22_X1 g883(.A1 (n_2), .A2 (Q[15]), .B1 (n_3), .B2 (D[15]), .ZN
       (n_22));
  INV_X1 g884(.I (n_20), .ZN (n_21));
  AOI22_X1 g885(.A1 (n_2), .A2 (Q[9]), .B1 (n_3), .B2 (D[9]), .ZN
       (n_20));
  INV_X1 g886(.I (n_18), .ZN (n_19));
  AOI22_X1 g887(.A1 (n_2), .A2 (Q[16]), .B1 (n_3), .B2 (D[16]), .ZN
       (n_18));
  INV_X1 g888(.I (n_16), .ZN (n_17));
  AOI22_X1 g889(.A1 (n_2), .A2 (Q[17]), .B1 (n_3), .B2 (D[17]), .ZN
       (n_16));
  INV_X1 g890(.I (n_14), .ZN (n_15));
  AOI22_X1 g891(.A1 (n_2), .A2 (Q[18]), .B1 (n_3), .B2 (D[18]), .ZN
       (n_14));
  INV_X1 g892(.I (n_12), .ZN (n_13));
  AOI22_X1 g893(.A1 (n_2), .A2 (Q[19]), .B1 (n_3), .B2 (D[19]), .ZN
       (n_12));
  INV_X1 g894(.I (n_10), .ZN (n_11));
  AOI22_X1 g895(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_10));
  INV_X1 g896(.I (n_8), .ZN (n_9));
  AOI22_X1 g897(.A1 (n_2), .A2 (Q[20]), .B1 (n_3), .B2 (D[20]), .ZN
       (n_8));
  INV_X1 g898(.I (n_6), .ZN (n_7));
  AOI22_X1 g899(.A1 (n_2), .A2 (Q[21]), .B1 (n_3), .B2 (D[21]), .ZN
       (n_6));
  INV_X1 g900(.I (n_4), .ZN (n_5));
  AOI22_X1 g901(.A1 (n_2), .A2 (Q[22]), .B1 (n_3), .B2 (D[22]), .ZN
       (n_4));
  NOR2_X1 g902(.A1 (n_1), .A2 (reset), .ZN (n_3));
  NOR2_X1 g903(.A1 (load), .A2 (reset), .ZN (n_2));
  INV_X1 g904(.I (load), .ZN (n_1));
endmodule

module vDFFRL_n32(clk, D, Q, reset, load);
  input clk, reset, load;
  input [31:0] D;
  output [31:0] Q;
  wire clk, reset, load;
  wire [31:0] D;
  wire [31:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_65), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[10] (.SN (1'b1), .CLK (clk), .D (n_53), .Q (Q[10]));
  DFFSNQ_X1 \Q_reg[11] (.SN (1'b1), .CLK (clk), .D (n_49), .Q (Q[11]));
  DFFSNQ_X1 \Q_reg[12] (.SN (1'b1), .CLK (clk), .D (n_39), .Q (Q[12]));
  DFFSNQ_X1 \Q_reg[13] (.SN (1'b1), .CLK (clk), .D (n_35), .Q (Q[13]));
  DFFSNQ_X1 \Q_reg[14] (.SN (1'b1), .CLK (clk), .D (n_31), .Q (Q[14]));
  DFFSNQ_X1 \Q_reg[15] (.SN (1'b1), .CLK (clk), .D (n_23), .Q (Q[15]));
  DFFSNQ_X1 \Q_reg[16] (.SN (1'b1), .CLK (clk), .D (n_19), .Q (Q[16]));
  DFFSNQ_X1 \Q_reg[17] (.SN (1'b1), .CLK (clk), .D (n_17), .Q (Q[17]));
  DFFSNQ_X1 \Q_reg[18] (.SN (1'b1), .CLK (clk), .D (n_15), .Q (Q[18]));
  DFFSNQ_X1 \Q_reg[19] (.SN (1'b1), .CLK (clk), .D (n_13), .Q (Q[19]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_11), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[20] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[20]));
  DFFSNQ_X1 \Q_reg[21] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[21]));
  DFFSNQ_X1 \Q_reg[22] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[22]));
  DFFSNQ_X1 \Q_reg[23] (.SN (1'b1), .CLK (clk), .D (n_63), .Q (Q[23]));
  DFFSNQ_X1 \Q_reg[24] (.SN (1'b1), .CLK (clk), .D (n_61), .Q (Q[24]));
  DFFSNQ_X1 \Q_reg[25] (.SN (1'b1), .CLK (clk), .D (n_59), .Q (Q[25]));
  DFFSNQ_X1 \Q_reg[26] (.SN (1'b1), .CLK (clk), .D (n_57), .Q (Q[26]));
  DFFSNQ_X1 \Q_reg[27] (.SN (1'b1), .CLK (clk), .D (n_55), .Q (Q[27]));
  DFFSNQ_X1 \Q_reg[28] (.SN (1'b1), .CLK (clk), .D (n_51), .Q (Q[28]));
  DFFSNQ_X1 \Q_reg[29] (.SN (1'b1), .CLK (clk), .D (n_47), .Q (Q[29]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_45), .Q (Q[2]));
  DFFSNQ_X1 \Q_reg[30] (.SN (1'b1), .CLK (clk), .D (n_43), .Q (Q[30]));
  DFFSNQ_X1 \Q_reg[31] (.SN (1'b1), .CLK (clk), .D (n_41), .Q (Q[31]));
  DFFSNQ_X1 \Q_reg[3] (.SN (1'b1), .CLK (clk), .D (n_37), .Q (Q[3]));
  DFFSNQ_X1 \Q_reg[4] (.SN (1'b1), .CLK (clk), .D (n_33), .Q (Q[4]));
  DFFSNQ_X1 \Q_reg[5] (.SN (1'b1), .CLK (clk), .D (n_29), .Q (Q[5]));
  DFFSNQ_X1 \Q_reg[6] (.SN (1'b1), .CLK (clk), .D (n_27), .Q (Q[6]));
  DFFSNQ_X1 \Q_reg[7] (.SN (1'b1), .CLK (clk), .D (n_25), .Q (Q[7]));
  DFFSNQ_X1 \Q_reg[8] (.SN (1'b1), .CLK (clk), .D (n_67), .Q (Q[8]));
  DFFSNQ_X1 \Q_reg[9] (.SN (1'b1), .CLK (clk), .D (n_21), .Q (Q[9]));
  INV_X1 g838(.I (n_66), .ZN (n_67));
  AOI22_X1 g839(.A1 (n_2), .A2 (Q[8]), .B1 (D[8]), .B2 (n_3), .ZN
       (n_66));
  INV_X1 g840(.I (n_64), .ZN (n_65));
  AOI22_X1 g841(.A1 (n_2), .A2 (Q[0]), .B1 (D[0]), .B2 (n_3), .ZN
       (n_64));
  INV_X1 g842(.I (n_62), .ZN (n_63));
  AOI22_X1 g843(.A1 (n_2), .A2 (Q[23]), .B1 (D[23]), .B2 (n_3), .ZN
       (n_62));
  INV_X1 g844(.I (n_60), .ZN (n_61));
  AOI22_X1 g845(.A1 (n_2), .A2 (Q[24]), .B1 (D[24]), .B2 (n_3), .ZN
       (n_60));
  INV_X1 g846(.I (n_58), .ZN (n_59));
  AOI22_X1 g847(.A1 (n_2), .A2 (Q[25]), .B1 (D[25]), .B2 (n_3), .ZN
       (n_58));
  INV_X1 g848(.I (n_56), .ZN (n_57));
  AOI22_X1 g849(.A1 (n_2), .A2 (Q[26]), .B1 (D[26]), .B2 (n_3), .ZN
       (n_56));
  INV_X1 g850(.I (n_54), .ZN (n_55));
  AOI22_X1 g851(.A1 (n_2), .A2 (Q[27]), .B1 (D[27]), .B2 (n_3), .ZN
       (n_54));
  INV_X1 g852(.I (n_52), .ZN (n_53));
  AOI22_X1 g853(.A1 (n_2), .A2 (Q[10]), .B1 (D[10]), .B2 (n_3), .ZN
       (n_52));
  INV_X1 g854(.I (n_50), .ZN (n_51));
  AOI22_X1 g855(.A1 (n_2), .A2 (Q[28]), .B1 (D[28]), .B2 (n_3), .ZN
       (n_50));
  INV_X1 g856(.I (n_48), .ZN (n_49));
  AOI22_X1 g857(.A1 (n_2), .A2 (Q[11]), .B1 (D[11]), .B2 (n_3), .ZN
       (n_48));
  INV_X1 g858(.I (n_46), .ZN (n_47));
  AOI22_X1 g859(.A1 (n_2), .A2 (Q[29]), .B1 (D[29]), .B2 (n_3), .ZN
       (n_46));
  INV_X1 g860(.I (n_44), .ZN (n_45));
  AOI22_X1 g861(.A1 (n_2), .A2 (Q[2]), .B1 (D[2]), .B2 (n_3), .ZN
       (n_44));
  INV_X1 g862(.I (n_42), .ZN (n_43));
  AOI22_X1 g863(.A1 (n_2), .A2 (Q[30]), .B1 (D[30]), .B2 (n_3), .ZN
       (n_42));
  INV_X1 g864(.I (n_40), .ZN (n_41));
  AOI22_X1 g865(.A1 (n_2), .A2 (Q[31]), .B1 (D[31]), .B2 (n_3), .ZN
       (n_40));
  INV_X1 g866(.I (n_38), .ZN (n_39));
  AOI22_X1 g867(.A1 (n_2), .A2 (Q[12]), .B1 (D[12]), .B2 (n_3), .ZN
       (n_38));
  INV_X1 g868(.I (n_36), .ZN (n_37));
  AOI22_X1 g869(.A1 (n_2), .A2 (Q[3]), .B1 (D[3]), .B2 (n_3), .ZN
       (n_36));
  INV_X1 g870(.I (n_34), .ZN (n_35));
  AOI22_X1 g871(.A1 (n_2), .A2 (Q[13]), .B1 (D[13]), .B2 (n_3), .ZN
       (n_34));
  INV_X1 g872(.I (n_32), .ZN (n_33));
  AOI22_X1 g873(.A1 (n_2), .A2 (Q[4]), .B1 (D[4]), .B2 (n_3), .ZN
       (n_32));
  INV_X1 g874(.I (n_30), .ZN (n_31));
  AOI22_X1 g875(.A1 (n_2), .A2 (Q[14]), .B1 (D[14]), .B2 (n_3), .ZN
       (n_30));
  INV_X1 g876(.I (n_28), .ZN (n_29));
  AOI22_X1 g877(.A1 (n_2), .A2 (Q[5]), .B1 (D[5]), .B2 (n_3), .ZN
       (n_28));
  INV_X1 g878(.I (n_26), .ZN (n_27));
  AOI22_X1 g879(.A1 (n_2), .A2 (Q[6]), .B1 (D[6]), .B2 (n_3), .ZN
       (n_26));
  INV_X1 g880(.I (n_24), .ZN (n_25));
  AOI22_X1 g881(.A1 (n_2), .A2 (Q[7]), .B1 (D[7]), .B2 (n_3), .ZN
       (n_24));
  INV_X1 g882(.I (n_22), .ZN (n_23));
  AOI22_X1 g883(.A1 (n_2), .A2 (Q[15]), .B1 (D[15]), .B2 (n_3), .ZN
       (n_22));
  INV_X1 g884(.I (n_20), .ZN (n_21));
  AOI22_X1 g885(.A1 (n_2), .A2 (Q[9]), .B1 (D[9]), .B2 (n_3), .ZN
       (n_20));
  INV_X1 g886(.I (n_18), .ZN (n_19));
  AOI22_X1 g887(.A1 (n_2), .A2 (Q[16]), .B1 (D[16]), .B2 (n_3), .ZN
       (n_18));
  INV_X1 g888(.I (n_16), .ZN (n_17));
  AOI22_X1 g889(.A1 (n_2), .A2 (Q[17]), .B1 (D[17]), .B2 (n_3), .ZN
       (n_16));
  INV_X1 g890(.I (n_14), .ZN (n_15));
  AOI22_X1 g891(.A1 (n_2), .A2 (Q[18]), .B1 (D[18]), .B2 (n_3), .ZN
       (n_14));
  INV_X1 g892(.I (n_12), .ZN (n_13));
  AOI22_X1 g893(.A1 (n_2), .A2 (Q[19]), .B1 (D[19]), .B2 (n_3), .ZN
       (n_12));
  INV_X1 g894(.I (n_10), .ZN (n_11));
  AOI22_X1 g895(.A1 (n_2), .A2 (Q[1]), .B1 (D[1]), .B2 (n_3), .ZN
       (n_10));
  INV_X1 g896(.I (n_8), .ZN (n_9));
  AOI22_X1 g897(.A1 (n_2), .A2 (Q[20]), .B1 (D[20]), .B2 (n_3), .ZN
       (n_8));
  INV_X1 g898(.I (n_6), .ZN (n_7));
  AOI22_X1 g899(.A1 (n_2), .A2 (Q[21]), .B1 (D[21]), .B2 (n_3), .ZN
       (n_6));
  INV_X1 g900(.I (n_4), .ZN (n_5));
  AOI22_X1 g901(.A1 (n_2), .A2 (Q[22]), .B1 (D[22]), .B2 (n_3), .ZN
       (n_4));
  NOR2_X1 g902(.A1 (n_1), .A2 (reset), .ZN (n_3));
  NOR2_X1 g903(.A1 (load), .A2 (reset), .ZN (n_2));
  INV_X1 g904(.I (load), .ZN (n_1));
endmodule

module vDFFRL_n3_22(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[2]));
  INV_X1 g109(.I (n_8), .ZN (n_9));
  AOI22_X1 g110(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_8));
  INV_X1 g111(.I (n_6), .ZN (n_7));
  AOI22_X1 g112(.A1 (n_2), .A2 (Q[0]), .B1 (n_3), .B2 (D[0]), .ZN
       (n_6));
  INV_X1 g113(.I (n_4), .ZN (n_5));
  AOI22_X1 g114(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_4));
  NOR2_X1 g115(.A1 (n_1), .A2 (reset), .ZN (n_3));
  NOR2_X1 g116(.A1 (load), .A2 (reset), .ZN (n_2));
  INV_X1 g117(.I (load), .ZN (n_1));
endmodule

module vDFFRL_n3_21(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[2]));
  SDFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_3), .SI (n_2),
       .SE (Q[0]), .Q (Q[0]));
  INV_X1 g110(.I (n_6), .ZN (n_7));
  AOI22_X1 g111(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_6));
  INV_X1 g112(.I (n_4), .ZN (n_5));
  AOI22_X1 g113(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_4));
  NOR2_X1 g114(.A1 (reset), .A2 (n_1), .ZN (n_3));
  NOR2_X1 g115(.A1 (reset), .A2 (load), .ZN (n_2));
  INV_X1 g116(.I (load), .ZN (n_1));
endmodule

module MUX3_n32(option0, option1, option2, sel, out);
  input [31:0] option0, option1, option2;
  input [1:0] sel;
  output [31:0] out;
  wire [31:0] option0, option1, option2;
  wire [1:0] sel;
  wire [31:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64;
  NAND2_X1 g898(.A1 (n_11), .A2 (n_50), .ZN (out[31]));
  NAND2_X1 g899(.A1 (n_20), .A2 (n_55), .ZN (out[29]));
  NAND2_X1 g900(.A1 (n_28), .A2 (n_59), .ZN (out[27]));
  NAND2_X1 g901(.A1 (n_31), .A2 (n_63), .ZN (out[23]));
  NAND2_X1 g902(.A1 (n_32), .A2 (n_64), .ZN (out[15]));
  NAND2_X1 g903(.A1 (n_30), .A2 (n_62), .ZN (out[14]));
  NAND2_X1 g904(.A1 (n_27), .A2 (n_60), .ZN (out[22]));
  NAND2_X1 g905(.A1 (n_29), .A2 (n_61), .ZN (out[13]));
  NAND2_X1 g906(.A1 (n_26), .A2 (n_58), .ZN (out[12]));
  NAND2_X1 g907(.A1 (n_18), .A2 (n_53), .ZN (out[26]));
  NAND2_X1 g908(.A1 (n_22), .A2 (n_56), .ZN (out[21]));
  NAND2_X1 g909(.A1 (n_23), .A2 (n_57), .ZN (out[11]));
  NAND2_X1 g910(.A1 (n_21), .A2 (n_54), .ZN (out[10]));
  NAND2_X1 g911(.A1 (n_17), .A2 (n_51), .ZN (out[20]));
  NAND2_X1 g912(.A1 (n_19), .A2 (n_52), .ZN (out[9]));
  NAND2_X1 g913(.A1 (n_16), .A2 (n_49), .ZN (out[8]));
  NAND2_X1 g914(.A1 (n_5), .A2 (n_42), .ZN (out[30]));
  NAND2_X1 g915(.A1 (n_9), .A2 (n_45), .ZN (out[25]));
  NAND2_X1 g916(.A1 (n_13), .A2 (n_47), .ZN (out[19]));
  NAND2_X1 g917(.A1 (n_14), .A2 (n_48), .ZN (out[7]));
  NAND2_X1 g918(.A1 (n_12), .A2 (n_46), .ZN (out[6]));
  NAND2_X1 g919(.A1 (n_25), .A2 (n_43), .ZN (out[18]));
  NAND2_X1 g920(.A1 (n_10), .A2 (n_44), .ZN (out[5]));
  NAND2_X1 g921(.A1 (n_8), .A2 (n_41), .ZN (out[4]));
  NAND2_X1 g922(.A1 (n_15), .A2 (n_38), .ZN (out[28]));
  NAND2_X1 g923(.A1 (n_6), .A2 (n_39), .ZN (out[17]));
  NAND2_X1 g924(.A1 (n_7), .A2 (n_40), .ZN (out[3]));
  NAND2_X1 g925(.A1 (n_37), .A2 (n_4), .ZN (out[2]));
  NAND2_X1 g926(.A1 (n_2), .A2 (n_36), .ZN (out[24]));
  NAND2_X1 g927(.A1 (n_35), .A2 (n_3), .ZN (out[1]));
  NAND2_X1 g928(.A1 (n_24), .A2 (n_34), .ZN (out[16]));
  NAND2_X1 g929(.A1 (n_33), .A2 (n_1), .ZN (out[0]));
  NAND2_X1 g930(.A1 (option0[15]), .A2 (n_0), .ZN (n_64));
  NAND2_X1 g931(.A1 (option0[23]), .A2 (n_0), .ZN (n_63));
  NAND2_X1 g932(.A1 (option0[14]), .A2 (n_0), .ZN (n_62));
  NAND2_X1 g933(.A1 (option0[13]), .A2 (n_0), .ZN (n_61));
  NAND2_X1 g934(.A1 (option0[22]), .A2 (n_0), .ZN (n_60));
  NAND2_X1 g935(.A1 (option0[27]), .A2 (n_0), .ZN (n_59));
  NAND2_X1 g936(.A1 (option0[12]), .A2 (n_0), .ZN (n_58));
  NAND2_X1 g937(.A1 (option0[11]), .A2 (n_0), .ZN (n_57));
  NAND2_X1 g938(.A1 (option0[21]), .A2 (n_0), .ZN (n_56));
  NAND2_X1 g939(.A1 (option0[29]), .A2 (n_0), .ZN (n_55));
  NAND2_X1 g940(.A1 (option0[10]), .A2 (n_0), .ZN (n_54));
  NAND2_X1 g941(.A1 (option0[26]), .A2 (n_0), .ZN (n_53));
  NAND2_X1 g942(.A1 (option0[9]), .A2 (n_0), .ZN (n_52));
  NAND2_X1 g943(.A1 (option0[20]), .A2 (n_0), .ZN (n_51));
  NAND2_X1 g944(.A1 (option0[31]), .A2 (n_0), .ZN (n_50));
  NAND2_X1 g945(.A1 (option0[8]), .A2 (n_0), .ZN (n_49));
  NAND2_X1 g946(.A1 (option0[7]), .A2 (n_0), .ZN (n_48));
  NAND2_X1 g947(.A1 (option0[19]), .A2 (n_0), .ZN (n_47));
  NAND2_X1 g948(.A1 (option0[6]), .A2 (n_0), .ZN (n_46));
  NAND2_X1 g949(.A1 (option0[25]), .A2 (n_0), .ZN (n_45));
  NAND2_X1 g950(.A1 (option0[5]), .A2 (n_0), .ZN (n_44));
  NAND2_X1 g951(.A1 (option0[18]), .A2 (n_0), .ZN (n_43));
  NAND2_X1 g952(.A1 (option0[30]), .A2 (n_0), .ZN (n_42));
  NAND2_X1 g953(.A1 (option0[4]), .A2 (n_0), .ZN (n_41));
  NAND2_X1 g954(.A1 (n_0), .A2 (option0[3]), .ZN (n_40));
  NAND2_X1 g955(.A1 (option0[17]), .A2 (n_0), .ZN (n_39));
  NAND2_X1 g956(.A1 (option0[28]), .A2 (n_0), .ZN (n_38));
  NAND2_X1 g957(.A1 (n_0), .A2 (option0[2]), .ZN (n_37));
  NAND2_X1 g958(.A1 (option0[24]), .A2 (n_0), .ZN (n_36));
  NAND2_X1 g959(.A1 (n_0), .A2 (option0[1]), .ZN (n_35));
  NAND2_X1 g960(.A1 (option0[16]), .A2 (n_0), .ZN (n_34));
  NAND2_X1 g961(.A1 (n_0), .A2 (option0[0]), .ZN (n_33));
  AOI22_X1 g962(.A1 (option1[15]), .A2 (sel[0]), .B1 (option2[15]), .B2
       (sel[1]), .ZN (n_32));
  AOI22_X1 g963(.A1 (option1[23]), .A2 (sel[0]), .B1 (option2[23]), .B2
       (sel[1]), .ZN (n_31));
  AOI22_X1 g964(.A1 (option1[14]), .A2 (sel[0]), .B1 (option2[14]), .B2
       (sel[1]), .ZN (n_30));
  AOI22_X1 g965(.A1 (option1[13]), .A2 (sel[0]), .B1 (option2[13]), .B2
       (sel[1]), .ZN (n_29));
  AOI22_X1 g966(.A1 (option1[27]), .A2 (sel[0]), .B1 (option2[27]), .B2
       (sel[1]), .ZN (n_28));
  AOI22_X1 g967(.A1 (option1[22]), .A2 (sel[0]), .B1 (option2[22]), .B2
       (sel[1]), .ZN (n_27));
  AOI22_X1 g968(.A1 (option1[12]), .A2 (sel[0]), .B1 (option2[12]), .B2
       (sel[1]), .ZN (n_26));
  AOI22_X1 g969(.A1 (option1[18]), .A2 (sel[0]), .B1 (option2[18]), .B2
       (sel[1]), .ZN (n_25));
  AOI22_X1 g970(.A1 (option1[16]), .A2 (sel[0]), .B1 (option2[16]), .B2
       (sel[1]), .ZN (n_24));
  AOI22_X1 g971(.A1 (option1[11]), .A2 (sel[0]), .B1 (option2[11]), .B2
       (sel[1]), .ZN (n_23));
  AOI22_X1 g972(.A1 (option1[21]), .A2 (sel[0]), .B1 (option2[21]), .B2
       (sel[1]), .ZN (n_22));
  AOI22_X1 g973(.A1 (option1[10]), .A2 (sel[0]), .B1 (option2[10]), .B2
       (sel[1]), .ZN (n_21));
  AOI22_X1 g974(.A1 (option1[29]), .A2 (sel[0]), .B1 (option2[29]), .B2
       (sel[1]), .ZN (n_20));
  AOI22_X1 g975(.A1 (option1[9]), .A2 (sel[0]), .B1 (option2[9]), .B2
       (sel[1]), .ZN (n_19));
  AOI22_X1 g976(.A1 (option1[26]), .A2 (sel[0]), .B1 (option2[26]), .B2
       (sel[1]), .ZN (n_18));
  AOI22_X1 g977(.A1 (option1[20]), .A2 (sel[0]), .B1 (option2[20]), .B2
       (sel[1]), .ZN (n_17));
  AOI22_X1 g978(.A1 (option1[8]), .A2 (sel[0]), .B1 (option2[8]), .B2
       (sel[1]), .ZN (n_16));
  AOI22_X1 g979(.A1 (option1[28]), .A2 (sel[0]), .B1 (option2[28]), .B2
       (sel[1]), .ZN (n_15));
  AOI22_X1 g980(.A1 (option1[7]), .A2 (sel[0]), .B1 (option2[7]), .B2
       (sel[1]), .ZN (n_14));
  AOI22_X1 g981(.A1 (option1[19]), .A2 (sel[0]), .B1 (option2[19]), .B2
       (sel[1]), .ZN (n_13));
  AOI22_X1 g982(.A1 (option1[6]), .A2 (sel[0]), .B1 (option2[6]), .B2
       (sel[1]), .ZN (n_12));
  AOI22_X1 g983(.A1 (option1[31]), .A2 (sel[0]), .B1 (option2[31]), .B2
       (sel[1]), .ZN (n_11));
  AOI22_X1 g984(.A1 (option1[5]), .A2 (sel[0]), .B1 (option2[5]), .B2
       (sel[1]), .ZN (n_10));
  AOI22_X1 g985(.A1 (option1[25]), .A2 (sel[0]), .B1 (option2[25]), .B2
       (sel[1]), .ZN (n_9));
  AOI22_X1 g986(.A1 (option1[4]), .A2 (sel[0]), .B1 (option2[4]), .B2
       (sel[1]), .ZN (n_8));
  AOI22_X1 g987(.A1 (option1[3]), .A2 (sel[0]), .B1 (option2[3]), .B2
       (sel[1]), .ZN (n_7));
  AOI22_X1 g988(.A1 (option1[17]), .A2 (sel[0]), .B1 (option2[17]), .B2
       (sel[1]), .ZN (n_6));
  AOI22_X1 g989(.A1 (option1[30]), .A2 (sel[0]), .B1 (option2[30]), .B2
       (sel[1]), .ZN (n_5));
  AOI22_X1 g990(.A1 (sel[0]), .A2 (option1[2]), .B1 (option2[2]), .B2
       (sel[1]), .ZN (n_4));
  AOI22_X1 g991(.A1 (sel[0]), .A2 (option1[1]), .B1 (sel[1]), .B2
       (option2[1]), .ZN (n_3));
  AOI22_X1 g992(.A1 (option1[24]), .A2 (sel[0]), .B1 (option2[24]), .B2
       (sel[1]), .ZN (n_2));
  AOI22_X1 g993(.A1 (sel[0]), .A2 (option1[0]), .B1 (sel[1]), .B2
       (option2[0]), .ZN (n_1));
  NOR2_X1 g994(.A1 (sel[0]), .A2 (sel[1]), .ZN (n_0));
endmodule

module vDFFRL_n3_23(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (D[0]), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (D[1]), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (D[2]), .Q (Q[2]));
endmodule

module MUX2_n3_14(option0, option1, sel, out);
  input [2:0] option0, option1;
  input sel;
  output [2:0] out;
  wire [2:0] option0, option1;
  wire sel;
  wire [2:0] out;
  wire n_0, n_1;
  NOR2_X1 g21(.A1 (sel), .A2 (n_0), .ZN (out[2]));
  NOR2_X1 g22(.A1 (sel), .A2 (n_1), .ZN (out[1]));
  OR2_X1 g23(.A1 (sel), .A2 (option0[0]), .Z (out[0]));
  INV_X1 g24(.I (option0[1]), .ZN (n_1));
  INV_X1 g25(.I (option0[2]), .ZN (n_0));
endmodule

module RNG_n3_15(clk, rst, min, max, out);
  input clk, rst;
  input [2:0] min, max;
  output [2:0] out;
  wire clk, rst;
  wire [2:0] min, max;
  wire [2:0] out;
  wire [2:0] nextnum;
  wire n_0, n_1, n_2, n_5, n_6, n_9;
  vDFFRL_n3_23 rnggendice(.clk (clk), .D (nextnum), .Q (out), .reset
       (1'b0), .load (1'b1));
  MUX2_n3_14 rngthresholddice(.option0 ({n_5, n_6, n_2}), .option1
       (3'b001), .sel (n_9), .out (nextnum));
  INV_X1 g32(.I (out[0]), .ZN (n_2));
  XNOR2_X1 g74(.A1 (n_0), .A2 (out[2]), .ZN (n_5));
  INV_X1 g75(.I (n_1), .ZN (n_9));
  AOI21_X1 g76(.A1 (out[1]), .A2 (out[2]), .B (rst), .ZN (n_1));
  XOR2_X1 g77(.A1 (out[0]), .A2 (out[1]), .Z (n_6));
  NAND2_X1 g78(.A1 (out[0]), .A2 (out[1]), .ZN (n_0));
endmodule

module vDFFRL_n3(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (D[0]), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (D[1]), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (D[2]), .Q (Q[2]));
endmodule

module MUX2_n3(option0, option1, sel, out);
  input [2:0] option0, option1;
  input sel;
  output [2:0] out;
  wire [2:0] option0, option1;
  wire sel;
  wire [2:0] out;
  wire n_0, n_1;
  NOR2_X1 g21(.A1 (sel), .A2 (n_0), .ZN (out[2]));
  NOR2_X1 g22(.A1 (sel), .A2 (n_1), .ZN (out[1]));
  OR2_X1 g23(.A1 (sel), .A2 (option0[0]), .Z (out[0]));
  INV_X1 g24(.I (option0[1]), .ZN (n_1));
  INV_X1 g25(.I (option0[2]), .ZN (n_0));
endmodule

module RNG_n3(clk, rst, min, max, out);
  input clk, rst;
  input [2:0] min, max;
  output [2:0] out;
  wire clk, rst;
  wire [2:0] min, max;
  wire [2:0] out;
  wire [2:0] nextnum;
  wire n_0, n_1, n_2, n_5, n_6, n_9;
  vDFFRL_n3 rnggendice(clk, nextnum, out, 1'b0, 1'b1);
  MUX2_n3 rngthresholddice({n_5, n_6, n_2}, 3'b001, n_9, nextnum);
  INV_X1 g34(.I (out[0]), .ZN (n_2));
  OR2_X1 g65(.A1 (n_1), .A2 (rst), .Z (n_9));
  HA_X1 g66(.A (out[2]), .B (n_0), .CO (n_1), .S (n_5));
  HA_X1 g67(.A (out[1]), .B (out[0]), .CO (n_0), .S (n_6));
endmodule

module geq_unsigned_19(A, B, Z);
  input [31:0] A, B;
  output Z;
  wire [31:0] A, B;
  wire Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93;
  OAI22_X1 g892(.A1 (n_93), .A2 (n_29), .B1 (n_11), .B2 (B[31]), .ZN
       (Z));
  AOI22_X1 g893(.A1 (n_92), .A2 (n_31), .B1 (A[30]), .B2 (n_14), .ZN
       (n_93));
  OAI22_X1 g894(.A1 (n_91), .A2 (B[29]), .B1 (n_90), .B2 (n_4), .ZN
       (n_92));
  AND2_X1 g895(.A1 (n_90), .A2 (n_4), .Z (n_91));
  AOI22_X1 g896(.A1 (n_89), .A2 (A[28]), .B1 (n_88), .B2 (n_18), .ZN
       (n_90));
  OR2_X1 g897(.A1 (n_88), .A2 (n_18), .Z (n_89));
  OAI22_X1 g898(.A1 (n_87), .A2 (B[27]), .B1 (n_86), .B2 (n_2), .ZN
       (n_88));
  AND2_X1 g899(.A1 (n_86), .A2 (n_2), .Z (n_87));
  AOI21_X1 g900(.A1 (n_83), .A2 (A[26]), .B (n_85), .ZN (n_86));
  NOR2_X1 g901(.A1 (n_84), .A2 (B[26]), .ZN (n_85));
  NOR2_X1 g902(.A1 (n_83), .A2 (A[26]), .ZN (n_84));
  OAI22_X1 g903(.A1 (n_82), .A2 (n_27), .B1 (n_16), .B2 (B[25]), .ZN
       (n_83));
  AOI22_X1 g904(.A1 (n_81), .A2 (n_35), .B1 (A[24]), .B2 (n_19), .ZN
       (n_82));
  OAI22_X1 g905(.A1 (n_80), .A2 (B[23]), .B1 (n_79), .B2 (n_22), .ZN
       (n_81));
  AND2_X1 g906(.A1 (n_79), .A2 (n_22), .Z (n_80));
  AOI21_X1 g907(.A1 (n_76), .A2 (A[22]), .B (n_78), .ZN (n_79));
  NOR2_X1 g908(.A1 (n_77), .A2 (B[22]), .ZN (n_78));
  NOR2_X1 g909(.A1 (n_76), .A2 (A[22]), .ZN (n_77));
  OAI22_X1 g910(.A1 (n_75), .A2 (B[21]), .B1 (n_74), .B2 (n_23), .ZN
       (n_76));
  AND2_X1 g911(.A1 (n_74), .A2 (n_23), .Z (n_75));
  AOI22_X1 g912(.A1 (n_73), .A2 (A[20]), .B1 (n_72), .B2 (n_17), .ZN
       (n_74));
  OR2_X1 g913(.A1 (n_72), .A2 (n_17), .Z (n_73));
  OAI22_X1 g914(.A1 (n_71), .A2 (B[19]), .B1 (n_70), .B2 (n_10), .ZN
       (n_72));
  AND2_X1 g915(.A1 (n_70), .A2 (n_10), .Z (n_71));
  AOI22_X1 g916(.A1 (n_69), .A2 (n_32), .B1 (A[18]), .B2 (n_24), .ZN
       (n_70));
  OAI22_X1 g917(.A1 (n_68), .A2 (B[17]), .B1 (n_67), .B2 (n_5), .ZN
       (n_69));
  AND2_X1 g918(.A1 (n_67), .A2 (n_5), .Z (n_68));
  AOI21_X1 g919(.A1 (n_64), .A2 (A[16]), .B (n_66), .ZN (n_67));
  NOR2_X1 g920(.A1 (n_65), .A2 (B[16]), .ZN (n_66));
  NOR2_X1 g921(.A1 (n_64), .A2 (A[16]), .ZN (n_65));
  OAI22_X1 g922(.A1 (n_63), .A2 (B[15]), .B1 (n_62), .B2 (n_7), .ZN
       (n_64));
  AND2_X1 g923(.A1 (n_62), .A2 (n_7), .Z (n_63));
  AOI22_X1 g924(.A1 (n_61), .A2 (A[14]), .B1 (n_60), .B2 (n_13), .ZN
       (n_62));
  OR2_X1 g925(.A1 (n_60), .A2 (n_13), .Z (n_61));
  OAI22_X1 g926(.A1 (n_59), .A2 (B[13]), .B1 (n_58), .B2 (n_15), .ZN
       (n_60));
  AND2_X1 g927(.A1 (n_58), .A2 (n_15), .Z (n_59));
  AOI22_X1 g928(.A1 (n_57), .A2 (n_34), .B1 (A[12]), .B2 (n_0), .ZN
       (n_58));
  OAI22_X1 g929(.A1 (n_56), .A2 (B[11]), .B1 (n_55), .B2 (n_8), .ZN
       (n_57));
  AND2_X1 g930(.A1 (n_55), .A2 (n_8), .Z (n_56));
  AOI22_X1 g931(.A1 (n_54), .A2 (A[10]), .B1 (n_53), .B2 (n_21), .ZN
       (n_55));
  OR2_X1 g932(.A1 (n_53), .A2 (n_21), .Z (n_54));
  OAI22_X1 g933(.A1 (n_52), .A2 (B[9]), .B1 (n_51), .B2 (n_9), .ZN
       (n_53));
  AND2_X1 g934(.A1 (n_51), .A2 (n_9), .Z (n_52));
  AOI21_X1 g935(.A1 (n_48), .A2 (A[8]), .B (n_50), .ZN (n_51));
  NOR2_X1 g936(.A1 (n_49), .A2 (B[8]), .ZN (n_50));
  NOR2_X1 g937(.A1 (n_48), .A2 (A[8]), .ZN (n_49));
  OAI22_X1 g938(.A1 (n_47), .A2 (B[7]), .B1 (n_46), .B2 (n_1), .ZN
       (n_48));
  AND2_X1 g939(.A1 (n_46), .A2 (n_1), .Z (n_47));
  AOI22_X1 g940(.A1 (n_45), .A2 (n_33), .B1 (A[6]), .B2 (n_20), .ZN
       (n_46));
  OAI22_X1 g941(.A1 (n_44), .A2 (B[5]), .B1 (n_43), .B2 (n_6), .ZN
       (n_45));
  AND2_X1 g942(.A1 (n_43), .A2 (n_6), .Z (n_44));
  AOI22_X1 g943(.A1 (n_42), .A2 (n_30), .B1 (A[4]), .B2 (n_25), .ZN
       (n_43));
  OAI22_X1 g944(.A1 (n_41), .A2 (B[3]), .B1 (n_40), .B2 (n_26), .ZN
       (n_42));
  AND2_X1 g945(.A1 (n_40), .A2 (n_26), .Z (n_41));
  AOI21_X1 g946(.A1 (n_37), .A2 (A[2]), .B (n_39), .ZN (n_40));
  NOR2_X1 g947(.A1 (n_38), .A2 (B[2]), .ZN (n_39));
  NOR2_X1 g948(.A1 (n_37), .A2 (A[2]), .ZN (n_38));
  OAI22_X1 g949(.A1 (n_36), .A2 (B[1]), .B1 (n_28), .B2 (n_12), .ZN
       (n_37));
  AND2_X1 g950(.A1 (n_28), .A2 (n_12), .Z (n_36));
  OR2_X1 g951(.A1 (A[24]), .A2 (n_19), .Z (n_35));
  OR2_X1 g952(.A1 (A[12]), .A2 (n_0), .Z (n_34));
  OR2_X1 g953(.A1 (A[6]), .A2 (n_20), .Z (n_33));
  OR2_X1 g954(.A1 (A[18]), .A2 (n_24), .Z (n_32));
  OR2_X1 g955(.A1 (A[30]), .A2 (n_14), .Z (n_31));
  OR2_X1 g956(.A1 (A[4]), .A2 (n_25), .Z (n_30));
  AND2_X1 g957(.A1 (n_11), .A2 (B[31]), .Z (n_29));
  NOR2_X1 g958(.A1 (A[0]), .A2 (n_3), .ZN (n_28));
  AND2_X1 g959(.A1 (n_16), .A2 (B[25]), .Z (n_27));
  INV_X1 g960(.I (A[3]), .ZN (n_26));
  INV_X1 g961(.I (B[4]), .ZN (n_25));
  INV_X1 g962(.I (B[18]), .ZN (n_24));
  INV_X1 g963(.I (A[21]), .ZN (n_23));
  INV_X1 g964(.I (A[23]), .ZN (n_22));
  INV_X1 g965(.I (B[10]), .ZN (n_21));
  INV_X1 g966(.I (B[6]), .ZN (n_20));
  INV_X1 g967(.I (B[24]), .ZN (n_19));
  INV_X1 g968(.I (B[28]), .ZN (n_18));
  INV_X1 g969(.I (B[20]), .ZN (n_17));
  INV_X1 g970(.I (A[25]), .ZN (n_16));
  INV_X1 g971(.I (A[13]), .ZN (n_15));
  INV_X1 g972(.I (B[30]), .ZN (n_14));
  INV_X1 g973(.I (B[14]), .ZN (n_13));
  INV_X1 g974(.I (A[1]), .ZN (n_12));
  INV_X1 g975(.I (A[31]), .ZN (n_11));
  INV_X1 g976(.I (A[19]), .ZN (n_10));
  INV_X1 g977(.I (A[9]), .ZN (n_9));
  INV_X1 g978(.I (A[11]), .ZN (n_8));
  INV_X1 g979(.I (A[15]), .ZN (n_7));
  INV_X1 g980(.I (A[5]), .ZN (n_6));
  INV_X1 g981(.I (A[17]), .ZN (n_5));
  INV_X1 g982(.I (A[29]), .ZN (n_4));
  INV_X1 g983(.I (B[0]), .ZN (n_3));
  INV_X1 g984(.I (A[27]), .ZN (n_2));
  INV_X1 g985(.I (A[7]), .ZN (n_1));
  INV_X1 g986(.I (B[12]), .ZN (n_0));
endmodule

module vDFFRL_n2(clk, D, Q, reset, load);
  input clk, reset, load;
  input [1:0] D;
  output [1:0] Q;
  wire clk, reset, load;
  wire [1:0] D;
  wire [1:0] Q;
  wire n_1, n_2, n_3, n_4, n_5;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_4), .Q (Q[1]));
  NOR2_X1 g90(.A1 (n_2), .A2 (reset), .ZN (n_5));
  NOR2_X1 g91(.A1 (n_3), .A2 (reset), .ZN (n_4));
  AOI22_X1 g92(.A1 (n_1), .A2 (Q[1]), .B1 (load), .B2 (D[1]), .ZN
       (n_3));
  XNOR2_X1 g93(.A1 (load), .A2 (Q[0]), .ZN (n_2));
  INV_X1 g94(.I (load), .ZN (n_1));
endmodule

module sub_unsigned_31(A, B, Z);
  input [31:0] A, B;
  output [31:0] Z;
  wire [31:0] A, B;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_35, n_36, n_38, n_39, n_41, n_42;
  wire n_44, n_45, n_47, n_48, n_50, n_51, n_53, n_54;
  wire n_56, n_57, n_59, n_60, n_62, n_63, n_65, n_66;
  wire n_68, n_69, n_71, n_72, n_74, n_75, n_77, n_78;
  wire n_80, n_81, n_83, n_84, n_86, n_87, n_89, n_90;
  wire n_92, n_93, n_95, n_96, n_98, n_99, n_101, n_102;
  wire n_104, n_105, n_107, n_108, n_110, n_111, n_113, n_114;
  wire n_116, n_117, n_119, n_120, n_122, n_123;
  XNOR2_X1 g883(.A1 (n_122), .A2 (n_33), .ZN (Z[31]));
  INV_X1 g884(.I (n_123), .ZN (Z[30]));
  FA_X1 g885(.A (n_11), .B (B[30]), .CI (n_119), .CO (n_122), .S
       (n_123));
  INV_X1 g886(.I (n_120), .ZN (Z[29]));
  FA_X1 g887(.A (n_18), .B (B[29]), .CI (n_116), .CO (n_119), .S
       (n_120));
  INV_X1 g888(.I (n_117), .ZN (Z[28]));
  FA_X1 g889(.A (n_15), .B (B[28]), .CI (n_113), .CO (n_116), .S
       (n_117));
  INV_X1 g890(.I (n_114), .ZN (Z[27]));
  FA_X1 g891(.A (n_3), .B (B[27]), .CI (n_110), .CO (n_113), .S
       (n_114));
  INV_X1 g892(.I (n_111), .ZN (Z[26]));
  FA_X1 g893(.A (n_4), .B (B[26]), .CI (n_107), .CO (n_110), .S
       (n_111));
  INV_X1 g894(.I (n_108), .ZN (Z[25]));
  FA_X1 g895(.A (n_19), .B (B[25]), .CI (n_104), .CO (n_107), .S
       (n_108));
  INV_X1 g896(.I (n_105), .ZN (Z[24]));
  FA_X1 g897(.A (n_27), .B (B[24]), .CI (n_101), .CO (n_104), .S
       (n_105));
  INV_X1 g898(.I (n_102), .ZN (Z[23]));
  FA_X1 g899(.A (n_13), .B (B[23]), .CI (n_98), .CO (n_101), .S
       (n_102));
  INV_X1 g900(.I (n_99), .ZN (Z[22]));
  FA_X1 g901(.A (n_21), .B (B[22]), .CI (n_95), .CO (n_98), .S (n_99));
  INV_X1 g902(.I (n_96), .ZN (Z[21]));
  FA_X1 g903(.A (n_24), .B (B[21]), .CI (n_92), .CO (n_95), .S (n_96));
  INV_X1 g904(.I (n_93), .ZN (Z[20]));
  FA_X1 g905(.A (n_26), .B (B[20]), .CI (n_89), .CO (n_92), .S (n_93));
  INV_X1 g906(.I (n_90), .ZN (Z[19]));
  FA_X1 g907(.A (n_5), .B (B[19]), .CI (n_86), .CO (n_89), .S (n_90));
  INV_X1 g908(.I (n_87), .ZN (Z[18]));
  FA_X1 g909(.A (n_23), .B (B[18]), .CI (n_83), .CO (n_86), .S (n_87));
  INV_X1 g910(.I (n_84), .ZN (Z[17]));
  FA_X1 g911(.A (n_28), .B (B[17]), .CI (n_80), .CO (n_83), .S (n_84));
  INV_X1 g912(.I (n_81), .ZN (Z[16]));
  FA_X1 g913(.A (n_1), .B (B[16]), .CI (n_77), .CO (n_80), .S (n_81));
  INV_X1 g914(.I (n_78), .ZN (Z[15]));
  FA_X1 g915(.A (n_9), .B (B[15]), .CI (n_74), .CO (n_77), .S (n_78));
  INV_X1 g916(.I (n_75), .ZN (Z[14]));
  FA_X1 g917(.A (n_12), .B (B[14]), .CI (n_71), .CO (n_74), .S (n_75));
  INV_X1 g918(.I (n_72), .ZN (Z[13]));
  FA_X1 g919(.A (n_0), .B (B[13]), .CI (n_68), .CO (n_71), .S (n_72));
  INV_X1 g920(.I (n_69), .ZN (Z[12]));
  FA_X1 g921(.A (n_8), .B (B[12]), .CI (n_65), .CO (n_68), .S (n_69));
  INV_X1 g922(.I (n_66), .ZN (Z[11]));
  FA_X1 g923(.A (n_7), .B (B[11]), .CI (n_62), .CO (n_65), .S (n_66));
  INV_X1 g924(.I (n_63), .ZN (Z[10]));
  FA_X1 g925(.A (n_25), .B (B[10]), .CI (n_59), .CO (n_62), .S (n_63));
  INV_X1 g926(.I (n_60), .ZN (Z[9]));
  FA_X1 g927(.A (n_20), .B (B[9]), .CI (n_56), .CO (n_59), .S (n_60));
  INV_X1 g928(.I (n_57), .ZN (Z[8]));
  FA_X1 g929(.A (n_22), .B (B[8]), .CI (n_53), .CO (n_56), .S (n_57));
  INV_X1 g930(.I (n_54), .ZN (Z[7]));
  FA_X1 g931(.A (n_10), .B (B[7]), .CI (n_50), .CO (n_53), .S (n_54));
  INV_X1 g932(.I (n_51), .ZN (Z[6]));
  FA_X1 g933(.A (n_17), .B (B[6]), .CI (n_47), .CO (n_50), .S (n_51));
  INV_X1 g934(.I (n_48), .ZN (Z[5]));
  FA_X1 g935(.A (n_29), .B (B[5]), .CI (n_44), .CO (n_47), .S (n_48));
  INV_X1 g936(.I (n_45), .ZN (Z[4]));
  FA_X1 g937(.A (n_30), .B (B[4]), .CI (n_41), .CO (n_44), .S (n_45));
  INV_X1 g938(.I (n_42), .ZN (Z[3]));
  FA_X1 g939(.A (n_14), .B (B[3]), .CI (n_38), .CO (n_41), .S (n_42));
  INV_X1 g940(.I (n_39), .ZN (Z[2]));
  FA_X1 g941(.A (n_2), .B (B[2]), .CI (n_35), .CO (n_38), .S (n_39));
  INV_X1 g942(.I (n_36), .ZN (Z[1]));
  FA_X1 g943(.A (n_16), .B (B[1]), .CI (n_32), .CO (n_35), .S (n_36));
  OAI21_X1 g944(.A1 (n_6), .A2 (B[0]), .B (n_31), .ZN (Z[0]));
  XNOR2_X1 g945(.A1 (A[31]), .A2 (B[31]), .ZN (n_33));
  INV_X1 g946(.I (n_31), .ZN (n_32));
  NAND2_X1 g947(.A1 (n_6), .A2 (B[0]), .ZN (n_31));
  INV_X1 g948(.I (A[4]), .ZN (n_30));
  INV_X1 g949(.I (A[5]), .ZN (n_29));
  INV_X1 g950(.I (A[17]), .ZN (n_28));
  INV_X1 g951(.I (A[24]), .ZN (n_27));
  INV_X1 g952(.I (A[20]), .ZN (n_26));
  INV_X1 g953(.I (A[10]), .ZN (n_25));
  INV_X1 g954(.I (A[21]), .ZN (n_24));
  INV_X1 g955(.I (A[18]), .ZN (n_23));
  INV_X1 g956(.I (A[8]), .ZN (n_22));
  INV_X1 g957(.I (A[22]), .ZN (n_21));
  INV_X1 g958(.I (A[9]), .ZN (n_20));
  INV_X1 g959(.I (A[25]), .ZN (n_19));
  INV_X1 g960(.I (A[29]), .ZN (n_18));
  INV_X1 g961(.I (A[6]), .ZN (n_17));
  INV_X1 g962(.I (A[1]), .ZN (n_16));
  INV_X1 g963(.I (A[28]), .ZN (n_15));
  INV_X1 g964(.I (A[3]), .ZN (n_14));
  INV_X1 g965(.I (A[23]), .ZN (n_13));
  INV_X1 g966(.I (A[14]), .ZN (n_12));
  INV_X1 g967(.I (A[30]), .ZN (n_11));
  INV_X1 g968(.I (A[7]), .ZN (n_10));
  INV_X1 g969(.I (A[15]), .ZN (n_9));
  INV_X1 g970(.I (A[12]), .ZN (n_8));
  INV_X1 g971(.I (A[11]), .ZN (n_7));
  INV_X1 g972(.I (A[0]), .ZN (n_6));
  INV_X1 g973(.I (A[19]), .ZN (n_5));
  INV_X1 g974(.I (A[26]), .ZN (n_4));
  INV_X1 g975(.I (A[27]), .ZN (n_3));
  INV_X1 g976(.I (A[2]), .ZN (n_2));
  INV_X1 g977(.I (A[16]), .ZN (n_1));
  INV_X1 g978(.I (A[13]), .ZN (n_0));
endmodule

module vDFFRL_n3_26(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[2]));
  INV_X1 g109(.I (n_8), .ZN (n_9));
  AOI22_X1 g110(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_8));
  INV_X1 g111(.I (n_6), .ZN (n_7));
  AOI22_X1 g112(.A1 (n_2), .A2 (Q[0]), .B1 (n_3), .B2 (D[0]), .ZN
       (n_6));
  INV_X1 g113(.I (n_4), .ZN (n_5));
  AOI22_X1 g114(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_4));
  NOR2_X1 g115(.A1 (reset), .A2 (n_1), .ZN (n_3));
  NOR2_X1 g116(.A1 (reset), .A2 (load), .ZN (n_2));
  INV_X1 g117(.I (load), .ZN (n_1));
endmodule

module vDFFRL_n3_25(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[2]));
  INV_X1 g109(.I (n_8), .ZN (n_9));
  AOI22_X1 g110(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_8));
  INV_X1 g111(.I (n_6), .ZN (n_7));
  AOI22_X1 g112(.A1 (n_2), .A2 (Q[0]), .B1 (n_3), .B2 (D[0]), .ZN
       (n_6));
  INV_X1 g113(.I (n_4), .ZN (n_5));
  AOI22_X1 g114(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_4));
  NOR2_X1 g115(.A1 (reset), .A2 (n_1), .ZN (n_3));
  NOR2_X1 g116(.A1 (reset), .A2 (load), .ZN (n_2));
  INV_X1 g117(.I (load), .ZN (n_1));
endmodule

module vDFFRL_n3_24(clk, D, Q, reset, load);
  input clk, reset, load;
  input [2:0] D;
  output [2:0] Q;
  wire clk, reset, load;
  wire [2:0] D;
  wire [2:0] Q;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9;
  DFFSNQ_X1 \Q_reg[0] (.SN (1'b1), .CLK (clk), .D (n_7), .Q (Q[0]));
  DFFSNQ_X1 \Q_reg[1] (.SN (1'b1), .CLK (clk), .D (n_9), .Q (Q[1]));
  DFFSNQ_X1 \Q_reg[2] (.SN (1'b1), .CLK (clk), .D (n_5), .Q (Q[2]));
  INV_X1 g109(.I (n_8), .ZN (n_9));
  AOI22_X1 g110(.A1 (n_2), .A2 (Q[1]), .B1 (n_3), .B2 (D[1]), .ZN
       (n_8));
  INV_X1 g111(.I (n_6), .ZN (n_7));
  AOI22_X1 g112(.A1 (n_2), .A2 (Q[0]), .B1 (n_3), .B2 (D[0]), .ZN
       (n_6));
  INV_X1 g113(.I (n_4), .ZN (n_5));
  AOI22_X1 g114(.A1 (n_2), .A2 (Q[2]), .B1 (n_3), .B2 (D[2]), .ZN
       (n_4));
  NOR2_X1 g115(.A1 (reset), .A2 (n_1), .ZN (n_3));
  NOR2_X1 g116(.A1 (reset), .A2 (load), .ZN (n_2));
  INV_X1 g117(.I (load), .ZN (n_1));
endmodule

module gamblinggame(clk, fundsbutton, fundsadded, betamount,
     startbutton, wheelbutton, rst, displayfunds, displaybet,
     displaywheel0, displaywheel1, displaywheel2, displaydice);
  input clk, fundsbutton, startbutton, wheelbutton, rst;
  input [31:0] fundsadded, betamount;
  output [31:0] displayfunds, displaybet;
  output [2:0] displaywheel0, displaywheel1, displaywheel2, displaydice;
  wire clk, fundsbutton, startbutton, wheelbutton, rst;
  wire [31:0] fundsadded, betamount;
  wire [31:0] displayfunds, displaybet;
  wire [2:0] displaywheel0, displaywheel1, displaywheel2, displaydice;
  wire [31:0] nextfunds;
  wire [2:0] rngdice;
  wire [2:0] dispensecounter;
  wire [2:0] rngwheel;
  wire [1:0] spincount;
  wire [7:0] ps;
  wire [7:0] ns;
  wire enoughfunds, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_77, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233;
  add_unsigned_29 add_29_30(.A (displayfunds), .B (displaybet), .Z
       ({n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160,
       n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169,
       n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178,
       n_179, n_180, n_181, n_182, n_183}));
  add_unsigned_29_18 add_29_52(.A (displayfunds), .B (fundsadded), .Z
       ({n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97,
       n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106,
       n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115,
       n_116, n_117, n_118, n_119}));
  vDFFRL_n32_27 betting(clk, betamount, displaybet, rst, n_72);
  vDFFRL_n32 credits(clk, nextfunds, displayfunds, rst, n_225);
  vDFFRL_n3_22 diceff(clk, rngdice, displaydice, rst, n_81);
  vDFFRL_n3_21 dispensecountff(clk, {n_79, n_80, 1'b0},
       dispensecounter, n_82, n_71);
  MUX3_n32 fundsmux({n_152, n_153, n_154, n_155, n_156, n_157, n_158,
       n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167,
       n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176,
       n_177, n_178, n_179, n_180, n_181, n_182, n_183}, {n_120, n_121,
       n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130,
       n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139,
       n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148,
       n_149, n_150, n_151}, {n_88, n_89, n_90, n_91, n_92, n_93, n_94,
       n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104,
       n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113,
       n_114, n_115, n_116, n_117, n_118, n_119}, {n_73, n_74},
       nextfunds);
  RNG_n3_15 generatedice(clk, rst, 3'b001, 3'b110, rngdice);
  RNG_n3 generatewheel(clk, rst, 3'b001, 3'b111, rngwheel);
  geq_unsigned_19 gte_30_33(.A (displayfunds), .B (betamount), .Z
       (enoughfunds));
  vDFFRL_n2 spincountff(clk, {n_83, 1'b0}, spincount, n_82, n_224);
  sub_unsigned_31 sub_29_41(.A (displayfunds), .B (displaybet), .Z
       ({n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128,
       n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137,
       n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146,
       n_147, n_148, n_149, n_150, n_151}));
  vDFFRL_n3_26 wheel0ff(clk, rngwheel, displaywheel0, n_87, n_86);
  vDFFRL_n3_25 wheel1ff(clk, rngwheel, displaywheel1, n_87, n_85);
  vDFFRL_n3_24 wheel2ff(clk, rngwheel, displaywheel2, n_87, n_84);
  INV_X1 g933(.I (n_229), .ZN (n_74));
  INV_X1 g932(.I (n_232), .ZN (n_73));
  INV_X1 g930(.I (n_233), .ZN (n_72));
  INV_X1 g931(.I (n_227), .ZN (n_71));
  NAND4_X1 g1478(.A1 (n_69), .A2 (n_233), .A3 (n_77), .A4 (n_231), .ZN
       (n_81));
  NAND2_X1 g1479(.A1 (n_70), .A2 (n_231), .ZN (n_87));
  NOR2_X1 g1480(.A1 (n_66), .A2 (n_82), .ZN (n_70));
  NAND3_X1 g1481(.A1 (n_233), .A2 (n_77), .A3 (n_56), .ZN (n_82));
  AND2_X1 g1482(.A1 (n_68), .A2 (spincount[1]), .Z (n_84));
  AND2_X1 g1483(.A1 (n_68), .A2 (n_220), .Z (n_86));
  NAND2_X1 g1484(.A1 (n_67), .A2 (n_227), .ZN (n_225));
  AND2_X1 g1485(.A1 (n_67), .A2 (n_228), .Z (n_69));
  NOR3_X1 g1486(.A1 (n_230), .A2 (spincount[1]), .A3 (n_57), .ZN
       (n_85));
  NOR2_X1 g1487(.A1 (n_230), .A2 (spincount[0]), .ZN (n_68));
  INV_X1 g1488(.I (n_66), .ZN (n_67));
  NAND2_X1 g1489(.A1 (n_229), .A2 (n_232), .ZN (n_66));
  OAI21_X1 g1490(.A1 (n_65), .A2 (ps[3]), .B (ps[2]), .ZN (n_77));
  NAND3_X1 g1491(.A1 (n_64), .A2 (n_226), .A3 (ps[2]), .ZN (n_228));
  XNOR2_X1 g1492(.A1 (n_58), .A2 (dispensecounter[2]), .ZN (n_79));
  NAND2_X1 g1493(.A1 (n_61), .A2 (n_65), .ZN (n_232));
  NAND2_X1 g1494(.A1 (n_59), .A2 (n_65), .ZN (n_227));
  NAND2_X1 g1495(.A1 (n_64), .A2 (n_61), .ZN (n_230));
  NAND2_X1 g1496(.A1 (n_63), .A2 (n_221), .ZN (n_229));
  NOR2_X1 g1497(.A1 (n_62), .A2 (n_221), .ZN (n_224));
  NAND2_X1 g1498(.A1 (n_59), .A2 (n_64), .ZN (n_231));
  NAND3_X1 g1499(.A1 (n_61), .A2 (n_221), .A3 (ps[0]), .ZN (n_233));
  NOR2_X1 g1500(.A1 (ps[0]), .A2 (ps[1]), .ZN (n_65));
  NOR2_X1 g1501(.A1 (n_221), .A2 (ps[0]), .ZN (n_64));
  INV_X1 g1502(.I (n_62), .ZN (n_63));
  NAND2_X1 g1503(.A1 (n_59), .A2 (ps[0]), .ZN (n_62));
  DFFSNQ_X1 \ps_reg[0] (.SN (1'b1), .CLK (clk), .D (n_60), .Q (ps[0]));
  OAI22_X1 g1505(.A1 (n_220), .A2 (spincount[0]), .B1 (spincount[1]),
       .B2 (n_57), .ZN (n_83));
  XNOR2_X1 g1506(.A1 (n_223), .A2 (dispensecounter[1]), .ZN (n_80));
  NOR2_X1 g1507(.A1 (ps[2]), .A2 (ps[3]), .ZN (n_61));
  OR2_X1 g1508(.A1 (ns[0]), .A2 (rst), .Z (n_60));
  NOR2_X1 g1509(.A1 (n_226), .A2 (ps[2]), .ZN (n_59));
  NAND2_X1 g1510(.A1 (dispensecounter[1]), .A2 (dispensecounter[0]),
       .ZN (n_58));
  INV_X1 g1511(.I (ps[1]), .ZN (n_221));
  INV_X1 g1512(.I (ps[2]), .ZN (n_222));
  INV_X1 g1513(.I (spincount[0]), .ZN (n_57));
  INV_X1 g1514(.I (spincount[1]), .ZN (n_220));
  INV_X1 g1515(.I (dispensecounter[0]), .ZN (n_223));
  INV_X1 g1516(.I (rst), .ZN (n_56));
  INV_X1 g1517(.I (ps[3]), .ZN (n_226));
  LHQ_X1 \ns_reg[0] (.E (n_77), .D (n_54), .Q (ns[0]));
  LHQ_X1 \ns_reg[3] (.E (n_77), .D (n_53), .Q (ns[3]));
  NAND4_X1 g2083(.A1 (n_51), .A2 (n_46), .A3 (n_229), .A4 (n_26), .ZN
       (n_54));
  NAND2_X1 g2084(.A1 (n_52), .A2 (n_46), .ZN (n_53));
  LHQ_X1 \ns_reg[1] (.E (n_77), .D (n_49), .Q (ns[1]));
  LHQ_X1 \ns_reg[2] (.E (n_77), .D (n_50), .Q (ns[2]));
  NOR4_X1 g2087(.A1 (n_47), .A2 (n_34), .A3 (n_35), .A4 (n_14), .ZN
       (n_52));
  NOR2_X1 g2088(.A1 (n_48), .A2 (n_13), .ZN (n_51));
  NAND4_X1 g2089(.A1 (n_45), .A2 (n_37), .A3 (n_33), .A4 (n_228), .ZN
       (n_50));
  AND4_X1 g2090(.A1 (n_44), .A2 (n_46), .A3 (n_229), .A4 (n_227), .Z
       (n_49));
  OAI21_X1 g2091(.A1 (n_43), .A2 (n_227), .B (n_41), .ZN (n_48));
  OAI21_X1 g2092(.A1 (n_42), .A2 (n_227), .B (n_232), .ZN (n_47));
  NAND3_X1 g2093(.A1 (n_38), .A2 (n_19), .A3 (n_221), .ZN (n_46));
  NAND3_X1 g2094(.A1 (n_39), .A2 (n_19), .A3 (n_221), .ZN (n_45));
  NOR4_X1 g2095(.A1 (n_21), .A2 (n_36), .A3 (n_13), .A4 (n_34), .ZN
       (n_44));
  INV_X1 g2096(.I (n_42), .ZN (n_43));
  OAI22_X1 g2097(.A1 (n_31), .A2 (n_40), .B1 (n_23), .B2 (n_2), .ZN
       (n_42));
  AOI22_X1 g2098(.A1 (n_30), .A2 (wheelbutton), .B1 (n_21), .B2 (n_3),
       .ZN (n_41));
  AOI21_X1 g2099(.A1 (displaydice[1]), .A2 (dispensecounter[1]), .B
       (n_29), .ZN (n_40));
  INV_X1 g2100(.I (n_38), .ZN (n_39));
  NAND3_X1 g2101(.A1 (n_32), .A2 (n_25), .A3 (n_18), .ZN (n_38));
  INV_X1 g2102(.I (n_36), .ZN (n_37));
  NOR3_X1 g2103(.A1 (n_26), .A2 (n_220), .A3 (wheelbutton), .ZN (n_36));
  NOR3_X1 g2104(.A1 (n_26), .A2 (spincount[1]), .A3 (wheelbutton), .ZN
       (n_35));
  NOR2_X1 g2105(.A1 (n_27), .A2 (wheelbutton), .ZN (n_34));
  NAND2_X1 g2106(.A1 (n_28), .A2 (wheelbutton), .ZN (n_33));
  AOI21_X1 g2107(.A1 (n_8), .A2 (displaywheel1[0]), .B (n_24), .ZN
       (n_32));
  AOI21_X1 g2108(.A1 (displaydice[2]), .A2 (dispensecounter[2]), .B
       (n_22), .ZN (n_31));
  NAND3_X1 g2109(.A1 (n_27), .A2 (n_230), .A3 (n_228), .ZN (n_30));
  OAI22_X1 g2110(.A1 (n_20), .A2 (n_223), .B1 (n_4), .B2
       (displaydice[1]), .ZN (n_29));
  INV_X1 g2111(.I (n_27), .ZN (n_28));
  NAND2_X1 g2112(.A1 (n_19), .A2 (ps[1]), .ZN (n_27));
  NAND4_X1 g2113(.A1 (n_226), .A2 (n_222), .A3 (ps[0]), .A4 (ps[1]),
       .ZN (n_26));
  AOI22_X1 g2114(.A1 (n_9), .A2 (displaywheel2[1]), .B1 (n_1), .B2
       (displaywheel0[2]), .ZN (n_25));
  OAI22_X1 g2115(.A1 (n_11), .A2 (displaywheel1[0]), .B1 (n_10), .B2
       (displaywheel2[1]), .ZN (n_24));
  INV_X1 g2116(.I (n_22), .ZN (n_23));
  XNOR2_X1 g2117(.A1 (n_12), .A2 (displaydice[2]), .ZN (n_22));
  DFFSNQ_X1 \ps_reg[1] (.SN (1'b1), .CLK (clk), .D (n_15), .Q (ps[1]));
  DFFSNQ_X1 \ps_reg[2] (.SN (1'b1), .CLK (clk), .D (n_17), .Q (ps[2]));
  DFFSNQ_X1 \ps_reg[3] (.SN (1'b1), .CLK (clk), .D (n_16), .Q (ps[3]));
  AOI21_X1 g2121(.A1 (enoughfunds), .A2 (startbutton), .B (n_233), .ZN
       (n_21));
  AOI21_X1 g2122(.A1 (n_4), .A2 (displaydice[1]), .B
       (dispensecounter[1]), .ZN (n_20));
  AND3_X2 g2123(.A1 (n_226), .A2 (ps[0]), .A3 (ps[2]), .Z (n_19));
  MUX2_X1 g2124(.I0 (n_1), .I1 (displaywheel0[2]), .S
       (displaywheel1[2]), .Z (n_18));
  NOR2_X1 g2125(.A1 (n_5), .A2 (rst), .ZN (n_17));
  NOR2_X1 g2126(.A1 (n_7), .A2 (rst), .ZN (n_16));
  NOR2_X1 g2127(.A1 (n_6), .A2 (rst), .ZN (n_15));
  NOR2_X1 g2128(.A1 (n_231), .A2 (n_3), .ZN (n_14));
  NOR2_X1 g2129(.A1 (n_231), .A2 (fundsbutton), .ZN (n_13));
  NOR2_X1 g2130(.A1 (displaydice[1]), .A2 (displaydice[0]), .ZN (n_12));
  NOR2_X1 g2131(.A1 (displaywheel2[0]), .A2 (displaywheel0[0]), .ZN
       (n_11));
  NOR2_X1 g2132(.A1 (displaywheel1[1]), .A2 (displaywheel0[1]), .ZN
       (n_10));
  NAND2_X1 g2133(.A1 (displaywheel0[1]), .A2 (displaywheel1[1]), .ZN
       (n_9));
  NAND2_X1 g2134(.A1 (displaywheel0[0]), .A2 (displaywheel2[0]), .ZN
       (n_8));
  INV_X1 g2135(.I (ns[3]), .ZN (n_7));
  INV_X1 g2136(.I (ns[1]), .ZN (n_6));
  INV_X1 g2137(.I (ns[2]), .ZN (n_5));
  INV_X1 g2138(.I (displaydice[0]), .ZN (n_4));
  INV_X1 g2139(.I (fundsbutton), .ZN (n_3));
  INV_X1 g2140(.I (dispensecounter[2]), .ZN (n_2));
  INV_X1 g2141(.I (displaywheel2[2]), .ZN (n_1));
endmodule

